export const FETCH_TYPES_REQUEST = 'FETCH_TYPES_REQUEST';
export const FETCH_TYPES_COMPLETE = 'FETCH_TYPES_COMPLETE';
export const FETCH_TYPES_ERROR = 'FETCH_TYPES_ERROR';
export const SET_TYPES = 'SET_TYPES';

export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_COMPLETE = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_ERROR = 'FETCH_ITEMS_REQUEST';
export const SET_ITEMS = 'SET_ITEMS';

export const FETCH_ITEMS_DATA_REQUEST = 'FETCH_ITEMS_DATA_REQUEST';
export const FETCH_ITEMS_DATA_COMPLETE = 'FETCH_ITEMS_DATA_COMPLETE';
export const FETCH_ITEMS_DATA_ERROR = 'FETCH_ITEMS_DATA_ERROR';
export const SET_ITEMS_DATA = 'SET_ITEMS_DATA';

export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_COMPLETE = 'FETCH_ORDERS_COMPLETE';
export const FETCH_ORDERS_ERROR = 'FETCH_ORDERS_ERROR';
export const SET_ORDERS = 'SET_ORDERS';

export const POST_NEW_ORDER_REQUEST = 'POST_NEW_ORDER_REQUEST';
export const POST_NEW_ORDER_COMPLETE = 'POST_NEW_ORDER_COMPLETE';
export const POST_NEW_ORDER_ERROR = 'POST_NEW_ORDER_ERROR';
export const ADD_ORDER = 'ADD_ORDER';

export const POST_ORDERS_UPDATE_REQUEST = 'POST_ORDERS_UPDATE_REQUEST';
export const POST_ORDERS_UPDATE_COMPLETE = 'POST_ORDERS_UPDATE_COMPLETE';
export const POST_ORDERS_UPDATE_ERROR = 'POST_ORDERS_UPDATE_ERROR';
export const UPDATE_ORDERS = 'UPDATE_ORDERS';
